### ISSUE TITLE
Sourcemod_Home Settings Don't Working

### ISSUE THREAD

**Issue by emreires** [Dreae/sourcepawn-vscode#2]
"sourcepawnLanguageServer.sourcemod_home": "D:/Sourcemod",

API include file found in addons/sourcemod/scripting/include.

But no hightlight, no syntax?!

**Comment by Dreae** [comment]
Can you confirm that the language is correctly set to SourcePawn for the file you're editing? Have you tried reloading the window?

The syntax highlighting shouldn't be affected by whether or not it can find the SourceMod API files.

**Comment by emreires** [comment]
I confirmed. Everything is okey.

sourcemod.inc is okey. All files are correct.

How can fix problem?

**Comment by emreires** [comment]
Fixed but working only for sourcemod.inc.

I tried CPrintToChat with #include <multicolors>. Not working for different includes.
